from pydantic import BaseModel, EmailStr, Field
from typing import List, Dict, Any, Optional
from datetime import datetime
from uuid import UUID

# 1. Input validator for triggering a loan request
class LoanRequest(BaseModel):
    user_id: str = Field(..., description="Unique customer identifier", example="usr_high")
    email: str = Field(..., description="Customer contact email address", example="customer.alice@gmail.com")
    phone: str = Field(..., description="Customer phone number", example="+1-555-0199")
    requested_amount: float = Field(..., gt=0, description="Requested loan principal amount", example=15000.0)

# 2. Output response returned immediately after agent processing
class LoanResponse(BaseModel):
    session_id: UUID = Field(..., description="Unique audit session identifier")
    status: str = Field(..., description="Final processing status (APPROVED / DENIED)")
    message: str = Field(..., description="Status summary message")

# 3. Step detail item in decision timeline
class StepResponse(BaseModel):
    step_type: str = Field(..., description="Type of step (THOUGHT / TOOL_CALL / TOOL_OUTPUT)")
    name: str = Field(..., description="Identifier name of node or tool")
    input_payload: Optional[Dict[str, Any]] = Field(default={}, description="Scrubbed input payload")
    output_payload: Optional[Dict[str, Any]] = Field(default={}, description="Scrubbed output result")
    created_at: datetime = Field(..., description="Timestamp of step execution")

    class Config:
        from_attributes = True

# 4. Detail view of a session timeline
class AuditTimelineResponse(BaseModel):
    session_id: UUID = Field(..., description="Session audit tracker")
    user_id: str = Field(..., description="User ID evaluated")
    requested_amount: float = Field(..., description="Requested amount")
    decision_status: str = Field(..., description="Final decision result")
    created_at: datetime = Field(..., description="Timestamp session started")
    timeline: List[StepResponse] = Field(..., description="Chronological log steps")

# 5. Output response for human-readable audit explanations
class ExplanationResponse(BaseModel):
    session_id: UUID = Field(..., description="Audit session identifier")
    explanation: str = Field(..., description="Plain-English explanation generated by the LLM")

# 6. Basic summary item returned in session searches
class SessionSummaryResponse(BaseModel):
    session_id: UUID
    user_id: str
    requested_amount: float
    decision_status: str
    created_at: datetime

    class Config:
        from_attributes = True
